# This is a basic workflow to help you get started with Actions

name: Push lyrics

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.API_TOKEN_NPLUS1 }} 
    - name: Push lyrics to NPlus1 repo
      run: |
        git clone git@github.com:annkamsk/nplus1.git
        cp -f *.md nplus1/src/pages/
        cd nplus1
        git config --global user.name "annkamsk"
        git config --global user.email "an.kramarska@gmail.com"
        git add .
        git commit -m "New files"
        git push
